#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define APP_PROTOCOL_SCHEMA_VERSION "axon.ihm.v1"

#ifndef APP_FIRMWARE_VERSION
#define APP_FIRMWARE_VERSION "0.1.0"
#endif

#define APP_DEVICE_ID_MAX_LEN 48
#define APP_TOPIC_PREFIX_MAX_LEN 64
#define APP_URI_MAX_LEN 192
#define APP_USERNAME_MAX_LEN 64
#define APP_PASSWORD_MAX_LEN 64
#define APP_SSID_MAX_LEN 32
#define APP_WIFI_PASSWORD_MAX_LEN 64
#define APP_HOSTNAME_MAX_LEN 64
#define APP_CODE_MAX_LEN 48
#define APP_MESSAGE_MAX_LEN 160
#define APP_COMMAND_ID_MAX_LEN 48
#define APP_SCHEDULE_ID_MAX_LEN 48
#define APP_REVISION_MAX_LEN 48
#define APP_TITLE_MAX_LEN 64
#define APP_REASON_MAX_LEN 32
#define APP_OTA_STATUS_MAX_LEN 32

#define APP_MAX_SCHEDULES 16
#define APP_MAX_EVENTS 10
#define APP_MAX_ERRORS 10

#define APP_HTTP_RECV_BUFFER_SIZE 2048
#define APP_HTTP_SEND_BUFFER_SIZE 2048
#define APP_HTTP_BODY_BUFFER_SIZE 2048

#define APP_LOCAL_SERVER_PORT_DEFAULT 8080
#define APP_MQTT_KEEPALIVE_SEC_DEFAULT 60
#define APP_WIFI_MAXIMUM_RETRY 5
#define APP_STATUS_PUBLISH_INTERVAL_MS 10000
#define APP_DIAGNOSTICS_PUBLISH_INTERVAL_MS 60000
#define APP_SCHEDULE_TASK_INTERVAL_MS 30000

#define APP_AP_SSID_PREFIX "AXON-IHM"
#define APP_AP_PASSWORD_DEFAULT "configure123"
#define APP_WIFI_STA_SSID_DEFAULT ""
#define APP_WIFI_STA_PASSWORD_DEFAULT ""

#define APP_MQTT_URI_DEFAULT "mqtts://broker.example.com"
#define APP_MQTT_USERNAME_DEFAULT ""
#define APP_MQTT_PASSWORD_DEFAULT ""
#define APP_TOPIC_PREFIX_DEFAULT "axon/ihm"

#define APP_LOCAL_SERVER_ENABLE_CORS_DEFAULT 1
#define APP_MQTT_ENABLED_DEFAULT 0
#define APP_MQTT_USE_TLS_DEFAULT 1
#define APP_WIFI_AP_FALLBACK_DEFAULT 1

#define APP_NVS_NAMESPACE_CONFIG "config"
#define APP_NVS_NAMESPACE_SCHEDULES "sched"

#define APP_OTA_TASK_STACK_SIZE 8192
#define APP_OTA_TASK_PRIORITY 5
#define APP_MAIN_TASK_STACK_SIZE 4096

#endif

